### ISSUE TITLE
undefined method `model_name' for ActiveMerchant::Billing::CreditCard:Class

### ISSUE THREAD

**Issue by bpokosh** [activemerchant/active_merchant#52]
When I use form_for with an ActiveMerchant::Billing::CreditCard I get the undefined method `model_name' error. I've tried monkeypatching various methods into the CreditCard class but haven't had any luck. This was working fine on 2.3.10 but I can't get it working on Rails 3.
